### ISSUE TITLE
Add  Learn More Section

### ISSUE THREAD

**Issue by sanjaysah101** [rmoghariya7/new-types-work-hackathon#2]
We need to add a `Learn More` page. 

The "Learn More" section should provide detailed information about the workshop. Here are some points you can include:

## Workshop Overview:

"Our pottery workshop is designed for beginners and hobbyists who want to learn the art of creating pottery from scratch. Whether you’ve never touched clay before or have some experience, this workshop is perfect for enhancing your skills."

## Why Join the Workshop?

"Unleash your creativity and express yourself through the art of pottery."
"Learn from experienced potters who will guide you through each step."
"Meet a community of like-minded enthusiasts and share your passion for art."
"Take home your unique pottery creations."

## What’s Included?

"All materials and tools will be provided, including a variety of clays, glazes, and pottery wheels."
"Access to instructional videos and resources even after the workshop."
"Receive a certificate of completion at the end of the workshop."
Workshop Structure:

"The workshop is divided into 6 sessions over 2 weeks, with each session focusing on a specific aspect of pottery making."
"Flexible scheduling options: Join weekend or weekday sessions as per your convenience."

**Comment by DinukaUdawela** [comment]
Hey dear, can you assign me for this task
