### ISSUE TITLE
Add About Us Section

### ISSUE THREAD

**Issue by sanjaysah101** [rmoghariya7/new-types-work-hackathon#3]
The "About Us" section can help potential participants learn more about the team and the philosophy behind the workshop:

## Who We Are:

"We are a team of passionate potters and artists dedicated to sharing the joy of pottery with others. With years of experience in the craft, we have conducted workshops across various communities and helped countless individuals discover their inner artist."

## Our Mission:

"Our mission is to make pottery accessible to everyone, nurturing creativity and mindfulness through the art of working with clay."

## Meet the Instructors:

Include short bios of the workshop instructors, highlighting their experience and specialties. For example:
"Sarah Williams - Master Potter with 10+ years of experience in wheel throwing and sculpting."
"John Doe - Specialized in surface decoration and glaze techniques."

## Our Studio:

"Located in the heart of [City], our studio is equipped with state-of-the-art pottery wheels, kilns, and a wide range of clay materials."

**Comment by DinukaUdawela** [comment]
Hey, can you assign me for this task

**Comment by Daksh-134** [comment]
Hi @sanjaysah101 pls assign this to me

**Comment by sanjaysah101** [comment]
Hi, @DinukaUdawela & @Daksh-134, This issue has been closed. You could contribute to https://github.com/ansopedia/creator-studio/issues
